// Datos de ejemplo para desarrollo local sin credenciales de Google.
// Los nombres de columnas son aproximados — se confirmarán contra los headers reales de la planilla.

export const mockHeaders = [
  'Nombre', 'Email', 'Teléfono', 'Fuente', 'Programa', 'Setter', 'Closer',
  'Monto Total', 'Cuotas',
  'Monto C1', 'Fecha C1', 'Método C1', 'Estado C1',
  'Monto C2', 'Fecha C2', 'Método C2', 'Estado C2',
  'Monto C3', 'Fecha C3', 'Método C3', 'Estado C3',
  'Monto C4', 'Fecha C4', 'Método C4', 'Estado C4',
  'Monto Pagado', 'Completado', 'Estatus', 'Cuotas Pagas', 'CRM', 'Contrato', 'Terminado',
  'Mes de Ingreso',
];

export const mockClientes = [
  {
    _rowIndex: 2,
    'Nombre': 'Martina López', 'Email': 'martina@email.com', 'Teléfono': '+54 11 2345-6789',
    'Fuente': 'ADS/Automática', 'Programa': 'M1', 'Setter': 'Ana', 'Closer': 'Kevin',
    'Monto Total': '1500', 'Cuotas': '2',
    'Monto C1': '750', 'Fecha C1': '05/04/2025', 'Método C1': 'Transferencia USD', 'Estado C1': 'SI',
    'Monto C2': '750', 'Fecha C2': '05/05/2025', 'Método C2': 'Transferencia USD', 'Estado C2': 'SI',
    'Monto Pagado': '1500', 'Completado': 'SI', 'Estatus': 'Activo',
    'Cuotas Pagas': '2', 'CRM': 'SI', 'Contrato': 'SI', 'Terminado': 'NO',
    'Mes de Ingreso': '2025-04',
  },
  {
    _rowIndex: 3,
    'Nombre': 'Carlos Ruiz', 'Email': 'carlos@email.com', 'Teléfono': '+54 11 3456-7890',
    'Fuente': 'IG-SETTER', 'Programa': 'M1+', 'Setter': 'Luis', 'Closer': 'Vicky',
    'Monto Total': '2000', 'Cuotas': '3',
    'Monto C1': '700', 'Fecha C1': '10/04/2025', 'Método C1': 'Wise', 'Estado C1': 'SI',
    'Monto C2': '650', 'Fecha C2': '10/05/2025', 'Método C2': 'Wise', 'Estado C2': 'SI',
    'Monto C3': '650', 'Fecha C3': '10/06/2025', 'Método C3': 'Wise', 'Estado C3': 'NO',
    'Monto C4': '', 'Fecha C4': '', 'Método C4': '', 'Estado C4': '',
    'Monto Pagado': '1350', 'Completado': 'NO', 'Estatus': 'Activo',
    'Cuotas Pagas': '2', 'CRM': 'SI', 'Contrato': 'SI', 'Terminado': 'NO',
    'Mes de Ingreso': '2025-04',
  },
  {
    _rowIndex: 4,
    'Nombre': 'Sofía Méndez', 'Email': 'sofia@email.com', 'Teléfono': '+1 305 555-1234',
    'Fuente': 'YOUTUBE', 'Programa': 'M1.1', 'Setter': 'Ana', 'Closer': 'Braian',
    'Monto Total': '3000', 'Cuotas': '1',
    'Monto C1': '3000', 'Fecha C1': '15/04/2025', 'Método C1': 'Stripe', 'Estado C1': 'SI',
    'Monto C2': '', 'Fecha C2': '', 'Método C2': '', 'Estado C2': '',
    'Monto C3': '', 'Fecha C3': '', 'Método C3': '', 'Estado C3': '',
    'Monto C4': '', 'Fecha C4': '', 'Método C4': '', 'Estado C4': '',
    'Monto Pagado': '3000', 'Completado': 'SI', 'Estatus': 'Activo',
    'Cuotas Pagas': '1', 'CRM': 'NO', 'Contrato': 'SI', 'Terminado': 'NO',
    'Mes de Ingreso': '2025-04',
  },
  {
    _rowIndex: 5,
    'Nombre': 'Diego Fernández', 'Email': 'diego@email.com', 'Teléfono': '+54 11 4567-8901',
    'Fuente': 'CRM-SETTER', 'Programa': 'M2', 'Setter': 'Luis', 'Closer': 'Kevin',
    'Monto Total': '4500', 'Cuotas': '4',
    'Monto C1': '1200', 'Fecha C1': '20/04/2025', 'Método C1': 'Transferencia USD', 'Estado C1': 'SI',
    'Monto C2': '1100', 'Fecha C2': '20/05/2025', 'Método C2': 'Transferencia USD', 'Estado C2': 'SI',
    'Monto C3': '1100', 'Fecha C3': '20/06/2025', 'Método C3': 'Transferencia USD', 'Estado C3': 'NO',
    'Monto C4': '1100', 'Fecha C4': '20/07/2025', 'Método C4': 'Transferencia USD', 'Estado C4': 'NO',
    'Monto Pagado': '2300', 'Completado': 'NO', 'Estatus': 'Activo',
    'Cuotas Pagas': '2', 'CRM': 'SI', 'Contrato': 'SI', 'Terminado': 'NO',
    'Mes de Ingreso': '2025-04',
  },
  {
    _rowIndex: 6,
    'Nombre': 'Laura Gómez', 'Email': 'laura@email.com', 'Teléfono': '+54 9 11 5678-9012',
    'Fuente': 'BIO', 'Programa': 'Back', 'Setter': '', 'Closer': 'Fabricio',
    'Monto Total': '1800', 'Cuotas': '2',
    'Monto C1': '900', 'Fecha C1': '01/05/2025', 'Método C1': 'PayPal/Payoneer', 'Estado C1': 'SI',
    'Monto C2': '900', 'Fecha C2': '01/06/2025', 'Método C2': 'PayPal/Payoneer', 'Estado C2': 'NO',
    'Monto C3': '', 'Fecha C3': '', 'Método C3': '', 'Estado C3': '',
    'Monto C4': '', 'Fecha C4': '', 'Método C4': '', 'Estado C4': '',
    'Monto Pagado': '900', 'Completado': 'NO', 'Estatus': 'Activo',
    'Cuotas Pagas': '1', 'CRM': 'SI', 'Contrato': 'SI', 'Terminado': 'NO',
    'Mes de Ingreso': '2025-05',
  },
  {
    _rowIndex: 7,
    'Nombre': 'Roberto Sánchez', 'Email': 'roberto@email.com', 'Teléfono': '+54 11 6789-0123',
    'Fuente': 'REPESCA', 'Programa': 'M1', 'Setter': 'Ana', 'Closer': 'Vicky',
    'Monto Total': '1500', 'Cuotas': '1',
    'Monto C1': '1500', 'Fecha C1': '05/05/2025', 'Método C1': 'Cripto', 'Estado C1': 'SI',
    'Monto C2': '', 'Fecha C2': '', 'Método C2': '', 'Estado C2': '',
    'Monto C3': '', 'Fecha C3': '', 'Método C3': '', 'Estado C3': '',
    'Monto C4': '', 'Fecha C4': '', 'Método C4': '', 'Estado C4': '',
    'Monto Pagado': '1500', 'Completado': 'SI', 'Estatus': 'Activo',
    'Cuotas Pagas': '1', 'CRM': 'NO', 'Contrato': 'NO', 'Terminado': 'NO',
    'Mes de Ingreso': '2025-05',
  },
  {
    _rowIndex: 8,
    'Nombre': 'Valentina Cruz', 'Email': 'vale@email.com', 'Teléfono': '+54 11 7890-1234',
    'Fuente': 'EMAIL', 'Programa': 'Starter', 'Setter': 'Luis', 'Closer': 'Braian',
    'Monto Total': '800', 'Cuotas': '2',
    'Monto C1': '400', 'Fecha C1': '12/05/2025', 'Método C1': 'Transferencia ARS', 'Estado C1': 'SI',
    'Monto C2': '400', 'Fecha C2': '12/06/2025', 'Método C2': 'Transferencia ARS', 'Estado C2': 'NO',
    'Monto C3': '', 'Fecha C3': '', 'Método C3': '', 'Estado C3': '',
    'Monto C4': '', 'Fecha C4': '', 'Método C4': '', 'Estado C4': '',
    'Monto Pagado': '400', 'Completado': 'NO', 'Estatus': 'Activo',
    'Cuotas Pagas': '1', 'CRM': 'SI', 'Contrato': 'SI', 'Terminado': 'NO',
    'Mes de Ingreso': '2025-05',
  },
];

export const mockEgresos = {
  'Egresos': [
    { _rowIndex: 2, 'Mes': '2025-04', 'Categoría': 'Sueldos',         'Monto': '8500',  '% Real': '34', '% Esperado': '30' },
    { _rowIndex: 3, 'Mes': '2025-04', 'Categoría': 'Publicidad',       'Monto': '4000',  '% Real': '16', '% Esperado': '20' },
    { _rowIndex: 4, 'Mes': '2025-04', 'Categoría': 'Apps',             'Monto': '500',   '% Real': '2',  '% Esperado': '3'  },
    { _rowIndex: 5, 'Mes': '2025-04', 'Categoría': 'Impuestos',        'Monto': '1200',  '% Real': '5',  '% Esperado': '5'  },
    { _rowIndex: 6, 'Mes': '2025-04', 'Categoría': 'Formación',        'Monto': '600',   '% Real': '2',  '% Esperado': '3'  },
    { _rowIndex: 7, 'Mes': '2025-04', 'Categoría': 'Gastos Admin',     'Monto': '800',   '% Real': '3',  '% Esperado': '3'  },
    { _rowIndex: 8, 'Mes': '2025-04', 'Categoría': 'Extras',           'Monto': '300',   '% Real': '1',  '% Esperado': '2'  },
    { _rowIndex: 9, 'Mes': '2025-04', 'Categoría': 'Retiros',          'Monto': '5000',  '% Real': '20', '% Esperado': '20' },
    { _rowIndex: 10, 'Mes': '2025-05', 'Categoría': 'Sueldos',         'Monto': '9200',  '% Real': '35', '% Esperado': '30' },
    { _rowIndex: 11, 'Mes': '2025-05', 'Categoría': 'Publicidad',       'Monto': '4500',  '% Real': '17', '% Esperado': '20' },
    { _rowIndex: 12, 'Mes': '2025-05', 'Categoría': 'Apps',             'Monto': '500',   '% Real': '2',  '% Esperado': '3'  },
    { _rowIndex: 13, 'Mes': '2025-05', 'Categoría': 'Impuestos',        'Monto': '1300',  '% Real': '5',  '% Esperado': '5'  },
    { _rowIndex: 14, 'Mes': '2025-05', 'Categoría': 'Formación',        'Monto': '700',   '% Real': '3',  '% Esperado': '3'  },
    { _rowIndex: 15, 'Mes': '2025-05', 'Categoría': 'Gastos Admin',     'Monto': '850',   '% Real': '3',  '% Esperado': '3'  },
    { _rowIndex: 16, 'Mes': '2025-05', 'Categoría': 'Extras',           'Monto': '200',   '% Real': '1',  '% Esperado': '2'  },
    { _rowIndex: 17, 'Mes': '2025-05', 'Categoría': 'Retiros',          'Monto': '5000',  '% Real': '19', '% Esperado': '20' },
  ],
  'Sueldos': [
    { _rowIndex: 2, 'Área': 'Comercial', 'Persona': 'Kevin',    'Fijo': '500', 'Comisión': '480', 'Total': '980'  },
    { _rowIndex: 3, 'Área': 'Comercial', 'Persona': 'Vicky',    'Fijo': '500', 'Comisión': '360', 'Total': '860'  },
    { _rowIndex: 4, 'Área': 'Comercial', 'Persona': 'Braian',   'Fijo': '500', 'Comisión': '240', 'Total': '740'  },
    { _rowIndex: 5, 'Área': 'Comercial', 'Persona': 'Fabricio', 'Fijo': '500', 'Comisión': '120', 'Total': '620'  },
    { _rowIndex: 6, 'Área': 'Entrega',   'Persona': 'Coach 1',  'Fijo': '1500','Comisión': '0',   'Total': '1500' },
    { _rowIndex: 7, 'Área': 'Ops/G&A',   'Persona': 'Admin 1',  'Fijo': '1200','Comisión': '0',   'Total': '1200' },
    { _rowIndex: 8, 'Área': 'Marketing', 'Persona': 'Mkt 1',    'Fijo': '1000','Comisión': '0',   'Total': '1000' },
  ],
};
